### ISSUE TITLE
Default terminal and find feature 

### ISSUE THREAD

**Issue by raffian** [Dhruvkumarshah/maven-dependency-explorer#6] opened 2023-01-03 23:41 UTC
vscode: **1.74.2**
maven-dependency-explorer: **1.0.13**
Windows 10/21H2

Find feature does not work accurately - results are hit or miss.

**Terminal**
Extension does not appear to use default terminal configured in vscode when executing `mvn` commands. My default terminal is `gitbash` but extension uses `cmd` - this failed initially since I did not have maven in my PATH for CMD terminal sessions.

**Comment by Dhruvkumarshah** [comment] 2023-04-29 17:43
The issue is fixed in the new 1.0.14 version. Here is the PR for the fix: [7](https://github.com/Dhruvkumarshah/maven-dependency-explorer/pull/7) created by @m-pavel. Thank you @m-pavel

**Closed by Dhruvkumarshah** 2023-04-29 17:43 UTC
