### ISSUE TITLE
Report an error after running the command

### ISSUE THREAD

**Issue by AirBashX** [Dhruvkumarshah/maven-dependency-explorer#1] opened 2021-06-19 05:44 UTC
Error: Command failed: mvn -f /C:/Users/ZSP/Desktop/spring-demo/pom.xml dependency:tree -DoutputFile=/c:/Users/ZSP/.vscode/extensions/dhruv.maven-dependency-explorer-1.0.9/dependency-tree.dot -DoutputType=dot
POM file "/C:/Users/ZSP/Desktop/spring-demo/pom.xml" specified the -f/--file command-line argument does not exist

**Comment by Dhruvkumarshah** [comment] 2021-06-19 13:35
@AirBashX , the issue is fixed in the latest version of plugin 1.0.10. Please try it out & let me know if the issue is still persisted.

**Closed by Dhruvkumarshah** 2021-06-19 13:35 UTC
Labels: bug

**Comment by victoraugustofd** [comment] 2023-12-27 17:16
Hi @Dhruvkumarshah, I tried to find the issue through the latest commits on file src/extension.ts, however to my lack of knowledge on this matter, I wasn't able to find on which commit this error returned. I am using version 1.0.17 and the issue with path containing spaces returned.
I will try to debug the code to find the issue and send a PR if I find it.
